### PR TITLE
use arrow function in data function

### PR DESCRIPTION
**Pull request by vinicius73**

### CODE REVIEW

**Comment by aidistan** [comment]
Two reasons against this PR:
1. We may need `this` context.
2. We may need some lines before returning.

**Comment by vinicius73** [comment]
Hi @aidistan 
1 -  Never need or use this in data function,  it is excuted one time only, in the init of component 
2 -  no need space wen use arrow functions 

This PR is based on recent vuejs's re-twieet 
https://twitter.com/vuejs/status/789599797527220224

**Comment by aidistan** [comment]
As the tweet said, it's a case for many situations. And according to my experiences, arrow function is not always appropriate.

Thanks for your PR, but I'm considering to change the script section to:

``` js
export default {
}
```

This snippet has raised so many discussions and PRs, which I think do not worth the time and trouble. What's your opinion? @hedefalk

**Comment by hedefalk** [comment]
Hm, I haven't actually used it a lot. Too bad it doesn't seem possible to use settings in snippets… A setting to decide which style you want would have been great…

Either way, you can override them with local settings, right?

**Comment by aidistan** [comment]
@hedefalk Yeah, users could still override them with local settings. 
@vinicius73 Thanks for the contribution. I will simplify the snippet after merging your PR.

**Comment by vinicius73** [comment]
I confess that in most cases remove all values. But I believe that many still use this shortcut.

**Pull request merged**
