### PR TITLE
Support custom kebab-case html tags

### LINKED ISSUE #7: Custom html tag does not work
image

See above, the tag `base-view`'s colour and indent are incorrect.

### PR DESCRIPTION
**Pull request by aidistan**
Close #7

### CODE REVIEW

**Comment by aidistan** [comment]
The syntax highlight still breaks when custom tags start with any `meta.tag.block.any.html` or `meta.tag.inline.any.html`.

**Comment by hedefalk** [comment]
lgtm!

**Comment by aidistan** [comment]
We could add `(?!-)` to following lines to fix custom tag highlight completely, but I have no idea how to fix the indent issue reported in #7.
- https://github.com/hedefalk/atom-vue/blob/master/grammars/vue.cson#L384
- https://github.com/hedefalk/atom-vue/blob/master/grammars/vue.cson#L402

**Comment by hedefalk** [comment]
@aidistan Cool! Please PR any additional things you want and I'll publish to apm as quick as I can. I'm at bit too busy too look into anything myself right now though. If I'm too slow and you want, I can give you push access?

**Comment by TheWaWaR** [comment]
image

After use your patch:
1. Auto indent still not working
2. `grid-view` matched the highlight, but `base-view` does not
   - I think it's because of below code matched the `base-view` first:

``` javascript
// Line: 402
{
  begin: "(</?)((?i:a|abbr|acronym|area|b|base|basefont|bdo|big|br|button|caption|cite|code|col|colgroup|del|dfn|em|font|head|html|i|img|input|ins|isindex|kbd|label|legend|li|link|map|meta|noscript|optgroup|option|param|q|s|samp|script|select|small|span|strike|strong|style|sub|sup|table|tbody|td|textarea|tfoot|th|thead|title|tr|tt|u|var)\\b)"
}
```

**Comment by aidistan** [comment]
@TheWaWaR The highlight was fixed in #9, but the indent issue remains.

I have reproduced the situation in `language-html`, which proves the issue is not related to this package.

selection_002

**Comment by aidistan** [comment]
@TheWaWaR Additionally, I would like to suggest you to use Jade in templates.

Life is short, why not to use a template language to save it ?  :smile:

**Comment by hedefalk** [comment]
0.5 published with this PR.

**Comment by TheWaWaR** [comment]
Jade can't auto indent~

**Pull request merged**
