### PR TITLE
add typescript and add more

### PR DESCRIPTION
**Pull request by puzzle9**
I think it might be more convenient

### CODE REVIEW

**Comment by hedefalk** [comment]
@puzzle9 Hi! So sorry I haven't looked at this. I'm not actually using Atom anymore and I definitely don't want to be an abandonware blocker. @aidistan have been the goto person here for quite some time?

@aidistan are you still around?

**Comment by puzzle9** [comment]
> @puzzle9 Hi! So sorry I haven't looked at this. I'm not actually using Atom anymore and I definitely don't want to be an abandonware blocker. @aidistan have been the goto person here for quite some time?
> 
> @aidistan are you still around?

Maybe because I think atom's code hints are very powerful
So are you using vscode, the first editor in the universe?

**Comment by hedefalk** [comment]
@puzzle9 You closed - don't want this merged anymore?
 
It seems @aidistan might not be around. To me it looks good and I can merge and release together with #108  if you want?

>Maybe because I think atom's code hints are very powerful
So are you using vscode, the first editor in the universe?

Based on your wording I feel you might have misunderstood me, but yes, I'm using vscode :)

PS. "abandonware blocker" was referring to me as the maintainer of this project, not Atom :)

**Comment by puzzle9** [comment]
> @puzzle9 You closed - don't want this merged anymore?
> 
> It seems @aidistan might not be around. To me it looks good and I can merge and release together with #108 if you want?
> 
> > Maybe because I think atom's code hints are very powerful
> > So are you using vscode, the first editor in the universe?
> 
> Based on your wording I feel you might have misunderstood me, but yes, I'm using vscode :)
> 
> PS. "abandonware blocker" was referring to me as the maintainer of this project, not Atom :)

sorry my english is bad

I use translation software to communicate with you
You may have misunderstood the meaning
I think atom is a good
vscode is goooooooooooooood

I think the two functions I added may affect other users
One is' typescript 'and the other is' nuxtjs'

**Pull request closed without merging**
